modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
issueTrackerURL="https://github.com/boredhero/morefuelsmod/issues"
modId="morefuelsmod"
version="§4§l1.7.1§r"
displayName='''§4§lMore Fuels Mod§r'''
displayURL="https://www.curseforge.com/minecraft/mc-mods/more-fuels-mod"
logoFile="mf_logo.png"
authors="§4Noah Martino A.K.A. boredhero§r"
description='''§4§oThe Premiere Mod that makes more items usable as fuel as well as adding fun fuel storage items and blocks!§r'''